name: Lua Scan on Push

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Lint and Test Lua Code
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Update Operating System
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm

      - name: Install administrator permission
        run: |
          pacman -S --noconfirm base-devel git sudo
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Install Arch User Repository
        run: git clone https://aur.archlinux.org/yay.git
        working-directory: ${{ github.workspace }}
        user: builder

      - name: Build Arch User Repository
        run: |
          cd yay
          makepkg -si --noconfirm
        working-directory: ${{ github.workspace }}
        user: builder

      - name: Install Build Tools and Environment
        run: |
          yay -S --noconfirm lua luarocks unzip zip
          luarocks install luacheck
          luarocks install busted

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Luacheck (Lint)
        run: |
          luacheck . || [ $? -eq 2 ]
