name: Lua Scan on Push

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Lint and Test Lua Code
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Update Operating System
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm 
      
      - name: Install AUR (Arch User Repository)
        run: |
          sudo pacman -S --noconfirm --needed base-devel git
          git clone https://aur.archlinux.org/yay.git
          cd yay
          makepkg -si --noconfirm

      - name: Install Build Tools and Environment
        run: |
          pacman -S --noconfirm base-devel lua luarocks git unzip zip
          luarocks install luacheck
          luarocks install busted

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Luacheck (Lint)
        run: |
          luacheck . || [ $? -eq 2 ]
