name: Lua Scan on Push

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Lint and Test Lua Code
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Update Operating System
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm 
      
      - name: Install AUR (Arch User Repository)
        run: |
          pacman -S --noconfirm --needed base-devel git
          git clone https://aur.archlinux.org/yay.git

      - name: Install NPM and Node.js
        run: |
          pacman -S nodejs npm --noconfirm 
          node -v 
          npm -v
          
      - name: Install Build Tools and Environment
        run: |
          pacman -S --noconfirm base-devel lua luarocks git unzip zip
          luarocks install luacheck
          luarocks install busted 

      - name: Install Interpreter Roblox
        run: |
          npm install roblox-ts
          npm install @uocdev/timestamp-hasei
          npm install @uocdev/math-fpe
          npm install chalk 
          npm fund

      - name: Startup Services 
        run: |
          node srvice.js
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Luacheck (Lint)
        run: |
          luacheck . || [ $? -eq 2 ]
