name: Lua Scan on Push

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Lint and Test Lua Code
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pacman and Keyring
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman-key --init
          pacman-key --populate archlinux

      - name: Update System
        run: pacman -Syu --noconfirm

      - name: Install Lua and Tools
        run: |
          pacman -S --noconfirm lua luarocks
          luarocks install luacheck
          luarocks install busted

      - name: Run Luacheck (Lint)
        run: |
          luacheck . || [ $? -eq 2 ]
